CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE app_user (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(50) NOT NULL,
    password_hash       VARCHAR(100) NOT NULL,
    role                VARCHAR(20) NOT NULL,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT ck_app_user_username CHECK (username = lower(username)),
    CONSTRAINT ck_app_user_role CHECK (role IN ('ADMIN', 'PICKER'))
);

CREATE TABLE device (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_code         VARCHAR(50) NOT NULL,
    description         VARCHAR(200) NOT NULL,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_device_code UNIQUE (device_code),
    CONSTRAINT ck_device_code CHECK (device_code = upper(device_code))
);

CREATE TABLE article (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                 VARCHAR(50) NOT NULL,
    description         VARCHAR(200) NOT NULL,
    qr_value            VARCHAR(100) NOT NULL,
    unit_of_measure     VARCHAR(10) NOT NULL DEFAULT 'EA',
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_article_sku UNIQUE (sku),
    CONSTRAINT uq_article_qr_value UNIQUE (qr_value),
    CONSTRAINT ck_article_sku CHECK (sku = upper(sku)),
    CONSTRAINT ck_article_sku_format CHECK (sku ~ '^[A-Z0-9_-]+$'),
    CONSTRAINT ck_article_qr_value CHECK (qr_value = 'ART:' || sku),
    CONSTRAINT ck_article_uom CHECK (unit_of_measure IN ('EA'))
);

CREATE TABLE location (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(20) NOT NULL,
    qr_value            VARCHAR(100) NOT NULL,
    pick_sequence       INTEGER NOT NULL,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_location_code UNIQUE (code),
    CONSTRAINT uq_location_qr_value UNIQUE (qr_value),
    CONSTRAINT uq_location_pick_sequence UNIQUE (pick_sequence),
    CONSTRAINT ck_location_code CHECK (code ~ '^[A-Z]+-[0-9]{2}-[0-9]{2}$'),
    CONSTRAINT ck_location_qr_value CHECK (qr_value = 'LOC:' || code),
    CONSTRAINT ck_location_pick_sequence CHECK (pick_sequence > 0)
);

CREATE TABLE stock (
    article_id          BIGINT NOT NULL REFERENCES article (id),
    location_id         BIGINT NOT NULL REFERENCES location (id),
    quantity            INTEGER NOT NULL,
    version             BIGINT NOT NULL DEFAULT 0,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id, location_id),
    CONSTRAINT ck_stock_quantity CHECK (quantity >= 0),
    CONSTRAINT ck_stock_version CHECK (version >= 0)
);

CREATE TABLE customer_order (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number        VARCHAR(50) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    created_by_user_id  BIGINT NOT NULL REFERENCES app_user (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at         TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_customer_order_number UNIQUE (order_number),
    CONSTRAINT ck_customer_order_number CHECK (order_number = upper(order_number)),
    CONSTRAINT ck_customer_order_status CHECK (
        status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED')
    ),
    CONSTRAINT ck_customer_order_dates CHECK (
        (status IN ('OPEN', 'IN_PROGRESS') AND released_at IS NOT NULL AND completed_at IS NULL)
        OR (status = 'COMPLETED' AND released_at IS NOT NULL AND completed_at IS NOT NULL)
    )
);

CREATE TABLE order_line (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT NOT NULL REFERENCES customer_order (id),
    line_number         INTEGER NOT NULL,
    article_id          BIGINT NOT NULL REFERENCES article (id),
    requested_quantity  INTEGER NOT NULL,
    picked_quantity     INTEGER NOT NULL DEFAULT 0,
    status              VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_order_line_number UNIQUE (order_id, line_number),
    CONSTRAINT uq_order_line_id_article UNIQUE (id, article_id),
    CONSTRAINT uq_order_line_movement_ref UNIQUE (id, order_id, article_id),
    CONSTRAINT ck_order_line_number CHECK (line_number > 0),
    CONSTRAINT ck_order_line_requested_quantity CHECK (requested_quantity > 0),
    CONSTRAINT ck_order_line_picked_quantity CHECK (
        picked_quantity >= 0 AND picked_quantity <= requested_quantity
    ),
    CONSTRAINT ck_order_line_status CHECK (
        status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED')
    ),
    CONSTRAINT ck_order_line_picked_state CHECK (
        (status = 'COMPLETED' AND picked_quantity = requested_quantity)
        OR (status <> 'COMPLETED')
    )
);

CREATE TABLE picking_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_number         VARCHAR(80) NOT NULL,
    order_line_id       BIGINT NOT NULL,
    task_sequence       INTEGER NOT NULL,
    article_id          BIGINT NOT NULL,
    source_location_id  BIGINT NOT NULL,
    requested_quantity  INTEGER NOT NULL,
    confirmed_quantity  INTEGER NOT NULL DEFAULT 0,
    status              VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    assigned_user_id    BIGINT REFERENCES app_user (id),
    assigned_device_id  BIGINT REFERENCES device (id),
    confirmation_id     UUID,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_at         TIMESTAMPTZ,
    location_confirmed_at TIMESTAMPTZ,
    article_confirmed_at  TIMESTAMPTZ,
    blocked_at           TIMESTAMPTZ,
    last_transition_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at        TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_picking_task_number UNIQUE (task_number),
    CONSTRAINT uq_picking_task_sequence UNIQUE (order_line_id, task_sequence),
    CONSTRAINT uq_picking_task_confirmation UNIQUE (confirmation_id),
    CONSTRAINT uq_picking_task_movement_ref
        UNIQUE (id, order_line_id, article_id, source_location_id),
    CONSTRAINT fk_picking_task_order_line_article
        FOREIGN KEY (order_line_id, article_id) REFERENCES order_line (id, article_id),
    CONSTRAINT fk_picking_task_stock
        FOREIGN KEY (article_id, source_location_id) REFERENCES stock (article_id, location_id),
    CONSTRAINT ck_picking_task_sequence CHECK (task_sequence > 0),
    CONSTRAINT ck_picking_task_requested_quantity CHECK (requested_quantity > 0),
    CONSTRAINT ck_picking_task_status CHECK (
        status IN (
            'AVAILABLE', 'ASSIGNED', 'LOCATION_CONFIRMED', 'ARTICLE_CONFIRMED',
            'BLOCKED', 'COMPLETED'
        )
    ),
    CONSTRAINT ck_picking_task_assignment CHECK (
        (status IN ('AVAILABLE', 'BLOCKED')
            AND assigned_user_id IS NULL AND assigned_device_id IS NULL AND assigned_at IS NULL)
        OR (status IN ('ASSIGNED', 'LOCATION_CONFIRMED', 'ARTICLE_CONFIRMED', 'COMPLETED')
            AND assigned_user_id IS NOT NULL AND assigned_device_id IS NOT NULL AND assigned_at IS NOT NULL)
    ),
    CONSTRAINT ck_picking_task_confirmation CHECK (
        (status = 'COMPLETED'
            AND confirmed_quantity = requested_quantity
            AND confirmation_id IS NOT NULL
            AND completed_at IS NOT NULL)
        OR (status <> 'COMPLETED'
            AND confirmed_quantity = 0
            AND confirmation_id IS NULL
            AND completed_at IS NULL)
    )
    , CONSTRAINT ck_picking_task_scan_timestamps CHECK (
        (status = 'AVAILABLE' AND location_confirmed_at IS NULL AND article_confirmed_at IS NULL AND blocked_at IS NULL)
        OR (status = 'ASSIGNED' AND location_confirmed_at IS NULL AND article_confirmed_at IS NULL AND blocked_at IS NULL)
        OR (status = 'LOCATION_CONFIRMED' AND location_confirmed_at IS NOT NULL AND article_confirmed_at IS NULL AND blocked_at IS NULL)
        OR (status IN ('ARTICLE_CONFIRMED', 'COMPLETED') AND location_confirmed_at IS NOT NULL AND article_confirmed_at IS NOT NULL AND blocked_at IS NULL)
        OR (status = 'BLOCKED' AND location_confirmed_at IS NULL AND article_confirmed_at IS NULL AND blocked_at IS NOT NULL)
    )
);

CREATE INDEX ix_customer_order_fifo
    ON customer_order (created_at, id)
    WHERE status IN ('OPEN', 'IN_PROGRESS');

CREATE INDEX ix_order_line_fifo
    ON order_line (order_id, line_number, id);

CREATE INDEX ix_picking_task_available
    ON picking_task (order_line_id, task_sequence, id)
    WHERE status = 'AVAILABLE';

CREATE UNIQUE INDEX uq_picking_task_active_user
    ON picking_task (assigned_user_id)
    WHERE status IN ('ASSIGNED', 'LOCATION_CONFIRMED', 'ARTICLE_CONFIRMED');

CREATE UNIQUE INDEX uq_picking_task_active_device
    ON picking_task (assigned_device_id)
    WHERE status IN ('ASSIGNED', 'LOCATION_CONFIRMED', 'ARTICLE_CONFIRMED');

CREATE TABLE task_transition (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    picking_task_id     BIGINT NOT NULL REFERENCES picking_task (id),
    previous_status     VARCHAR(30),
    new_status          VARCHAR(30) NOT NULL,
    actor_user_id       BIGINT REFERENCES app_user (id),
    device_id           BIGINT REFERENCES device (id),
    reason              VARCHAR(500),
    correlation_id      UUID NOT NULL DEFAULT gen_random_uuid(),
    confirmation_id     UUID,
    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_task_transition_status CHECK (
        new_status IN ('AVAILABLE', 'ASSIGNED', 'LOCATION_CONFIRMED', 'ARTICLE_CONFIRMED', 'BLOCKED', 'COMPLETED')
        AND (previous_status IS NULL OR previous_status IN ('AVAILABLE', 'ASSIGNED', 'LOCATION_CONFIRMED', 'ARTICLE_CONFIRMED', 'BLOCKED', 'COMPLETED'))
    ),
    CONSTRAINT ck_task_transition_block_reason CHECK (
        (new_status <> 'BLOCKED' OR reason IS NOT NULL)
    )
);

CREATE INDEX ix_task_transition_task_time
    ON task_transition (picking_task_id, occurred_at, id);

CREATE TABLE auth_token (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token_hash          CHAR(64) NOT NULL,
    user_id             BIGINT NOT NULL REFERENCES app_user (id),
    device_id           BIGINT NOT NULL REFERENCES device (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at          TIMESTAMPTZ NOT NULL,
    last_used_at        TIMESTAMPTZ,
    revoked_at          TIMESTAMPTZ,
    CONSTRAINT uq_auth_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_auth_token_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_auth_token_revocation CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX ix_auth_token_active_lookup
    ON auth_token (token_hash, expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE stock_movement (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_type       VARCHAR(30) NOT NULL,
    article_id          BIGINT NOT NULL,
    location_id         BIGINT NOT NULL,
    quantity_delta      INTEGER NOT NULL,
    resulting_quantity  INTEGER NOT NULL,
    order_id            BIGINT,
    order_line_id       BIGINT,
    picking_task_id     BIGINT,
    performed_by_user_id BIGINT NOT NULL REFERENCES app_user (id),
    device_id           BIGINT REFERENCES device (id),
    reason              VARCHAR(500) NOT NULL,
    correlation_id      UUID NOT NULL DEFAULT gen_random_uuid(),
    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_movement_stock
        FOREIGN KEY (article_id, location_id) REFERENCES stock (article_id, location_id),
    CONSTRAINT fk_stock_movement_order_line
        FOREIGN KEY (order_line_id, order_id, article_id)
        REFERENCES order_line (id, order_id, article_id),
    CONSTRAINT fk_stock_movement_task
        FOREIGN KEY (picking_task_id, order_line_id, article_id, location_id)
        REFERENCES picking_task (id, order_line_id, article_id, source_location_id),
    CONSTRAINT uq_stock_movement_task_pick UNIQUE (picking_task_id),
    CONSTRAINT ck_stock_movement_type CHECK (
        movement_type IN ('INITIAL_STOCK', 'RECEIPT', 'PICK', 'ADJUSTMENT')
    ),
    CONSTRAINT ck_stock_movement_result CHECK (resulting_quantity >= 0),
    CONSTRAINT ck_stock_movement_semantics CHECK (
        (movement_type = 'INITIAL_STOCK'
            AND quantity_delta > 0
            AND resulting_quantity = quantity_delta
            AND order_id IS NULL
            AND order_line_id IS NULL
            AND picking_task_id IS NULL
            AND device_id IS NULL)
        OR (movement_type = 'RECEIPT'
            AND quantity_delta > 0
            AND order_id IS NULL
            AND order_line_id IS NULL
            AND picking_task_id IS NULL
            AND device_id IS NULL)
        OR (movement_type = 'ADJUSTMENT'
            AND quantity_delta <> 0
            AND order_id IS NULL
            AND order_line_id IS NULL
            AND picking_task_id IS NULL
            AND device_id IS NULL)
        OR (movement_type = 'PICK'
            AND quantity_delta < 0
            AND order_id IS NOT NULL
            AND order_line_id IS NOT NULL
            AND picking_task_id IS NOT NULL
            AND device_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_stock_movement_initial
    ON stock_movement (article_id, location_id)
    WHERE movement_type = 'INITIAL_STOCK';

CREATE INDEX ix_stock_movement_article_location_time
    ON stock_movement (article_id, location_id, occurred_at, id);

CREATE INDEX ix_stock_movement_order_trace
    ON stock_movement (order_id, order_line_id, picking_task_id);

CREATE OR REPLACE FUNCTION validate_stock_movement_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM stock s
        WHERE s.article_id = NEW.article_id
          AND s.location_id = NEW.location_id
          AND s.quantity = NEW.resulting_quantity
    ) THEN
        RAISE EXCEPTION 'movement resulting quantity does not match current stock'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.movement_type = 'PICK' AND NOT EXISTS (
        SELECT 1
        FROM picking_task t
        WHERE t.id = NEW.picking_task_id
          AND t.order_line_id = NEW.order_line_id
          AND t.article_id = NEW.article_id
          AND t.source_location_id = NEW.location_id
          AND t.status = 'COMPLETED'
          AND NEW.quantity_delta = -t.confirmed_quantity
    ) THEN
        RAISE EXCEPTION 'pick movement does not match its completed task'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_stock_movement_validate_insert
BEFORE INSERT ON stock_movement
FOR EACH ROW EXECUTE FUNCTION validate_stock_movement_insert();

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_customer_order_updated_at
BEFORE UPDATE ON customer_order
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_order_line_updated_at
BEFORE UPDATE ON order_line
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION set_picking_task_timestamps()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    IF NEW.status IS DISTINCT FROM OLD.status THEN
        NEW.last_transition_at := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_picking_task_timestamps
BEFORE UPDATE ON picking_task
FOR EACH ROW EXECUTE FUNCTION set_picking_task_timestamps();

CREATE OR REPLACE FUNCTION reject_stock_movement_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'stock_movement is append-only; % is forbidden', TG_OP
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_stock_movement_append_only
BEFORE UPDATE OR DELETE ON stock_movement
FOR EACH ROW EXECUTE FUNCTION reject_stock_movement_mutation();

CREATE TRIGGER trg_task_transition_append_only
BEFORE UPDATE OR DELETE ON task_transition
FOR EACH ROW EXECUTE FUNCTION reject_stock_movement_mutation();

COMMENT ON TABLE stock_movement IS
    'Append-only audit ledger. Every stock quantity change must append exactly one row.';
COMMENT ON TABLE task_transition IS
    'Append-only audit ledger for picking-task state transitions.';
COMMENT ON COLUMN picking_task.confirmation_id IS
    'HHT-generated idempotency identifier retained across confirmation retries.';
