-- MFC work package (ADR 0011, TELEGRAMS.md v1). V1 stays untouched; this
-- migration only adds schema, matching the immutable-migration rule.

-- Additive role for the WCS confirmation client (ADR 0011): the existing
-- bearer-token scheme (ADR 0005) is reused rather than a parallel auth path.
ALTER TABLE app_user DROP CONSTRAINT ck_app_user_role;
ALTER TABLE app_user ADD CONSTRAINT ck_app_user_role CHECK (role IN ('ADMIN', 'PICKER', 'WCS'));

CREATE TABLE mfc_mission (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                    UUID NOT NULL,
    mission_type                VARCHAR(20) NOT NULL,
    state                       VARCHAR(20) NOT NULL,
    order_id                    BIGINT NOT NULL REFERENCES customer_order (id),
    order_number                VARCHAR(50) NOT NULL,
    source_location_id          BIGINT NOT NULL REFERENCES location (id),
    destination_location_id     BIGINT NOT NULL REFERENCES location (id),
    attempts                    INTEGER NOT NULL DEFAULT 0,
    next_attempt_at             TIMESTAMPTZ,
    last_error                  VARCHAR(500),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mfc_mission_event UNIQUE (event_id),
    CONSTRAINT ck_mfc_mission_type CHECK (mission_type IN ('TRANSPORT', 'SORT')),
    CONSTRAINT ck_mfc_mission_state CHECK (
        state IN ('PENDING', 'DISPATCHED', 'ACCEPTED', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_mfc_mission_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_mfc_mission_locations CHECK (source_location_id <> destination_location_id)
);

-- Defensive guarantee (mirrors uq_stock_movement_task_pick): at most one
-- TRANSPORT mission per completed order. Application code already enforces
-- this by construction (publish() fires exactly once, at order completion),
-- this is the database-level backstop.
CREATE UNIQUE INDEX uq_mfc_mission_order_transport
    ON mfc_mission (order_id)
    WHERE mission_type = 'TRANSPORT';

-- FAILED is terminal (dispatch exhaustion is not retried further, only a
-- WCS-side reprocess would revisit it); only PENDING rows are ever reclaimed.
CREATE INDEX ix_mfc_mission_dispatch_queue
    ON mfc_mission (next_attempt_at, id)
    WHERE state = 'PENDING';

CREATE TRIGGER trg_mfc_mission_updated_at
BEFORE UPDATE ON mfc_mission
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE mfc_mission_transition (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mfc_mission_id      BIGINT NOT NULL REFERENCES mfc_mission (id),
    previous_state      VARCHAR(20),
    new_state           VARCHAR(20) NOT NULL,
    reason              VARCHAR(500),
    correlation_id      UUID NOT NULL DEFAULT gen_random_uuid(),
    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_mfc_mission_transition_state CHECK (
        new_state IN ('PENDING', 'DISPATCHED', 'ACCEPTED', 'COMPLETED', 'FAILED')
        AND (previous_state IS NULL OR previous_state IN ('PENDING', 'DISPATCHED', 'ACCEPTED', 'COMPLETED', 'FAILED'))
    ),
    CONSTRAINT ck_mfc_mission_transition_failure_reason CHECK (
        new_state <> 'FAILED' OR reason IS NOT NULL
    )
);

CREATE INDEX ix_mfc_mission_transition_mission_time
    ON mfc_mission_transition (mfc_mission_id, occurred_at, id);

CREATE OR REPLACE FUNCTION reject_mfc_mission_transition_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'mfc_mission_transition is append-only; % is forbidden', TG_OP
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_mfc_mission_transition_append_only
BEFORE UPDATE OR DELETE ON mfc_mission_transition
FOR EACH ROW EXECUTE FUNCTION reject_mfc_mission_transition_mutation();

COMMENT ON TABLE mfc_mission IS
    'Transactional outbox for MFC mission telegrams (ADR 0011). One row per
    emitted mission; PENDING rows are written in the same transaction that
    completes the order, and dispatched/confirmed asynchronously.';
COMMENT ON TABLE mfc_mission_transition IS
    'Append-only audit ledger of mfc_mission state changes, mirroring task_transition.';
